---
name: Build and push docker images

env:
  DOCKERHUB_REPOSITORY: traccar/traccar

on:
  push:
    branches: ["v[0-9]+.[0-9]+.[0-9]+"]

defaults:
  run:
    shell: bash

jobs:
  docker-build-push:
    name: Build and push docker images
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: [alpine, debian, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set environment DOCKERHUB_IMAGE_TAGS
        if: github.ref != 'refs/heads/master'
        run: |
          _VERSION=${GITHUB_REF_NAME#v*}
          _VERSION_MAJOR_MINOR=${_VERSION%.*}
          _VERSION_MAJOR=${_VERSION_MAJOR_MINOR%.*}
          _DOCKERHUB_IMAGE_TAGS="$DOCKERHUB_REPOSITORY:$_VERSION-${{ matrix.os }}"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION_MAJOR_MINOR-${{ matrix.os }}"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION_MAJOR-${{ matrix.os }}"
          _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:${{ matrix.os }}"
          if [ "${{ matrix.os }}" == "alpine" ]; then
            _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION"
            _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION_MAJOR_MINOR"
            _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:$_VERSION_MAJOR"
            _DOCKERHUB_IMAGE_TAGS+=",$DOCKERHUB_REPOSITORY:latest"
          fi
          echo "DOCKERHUB_IMAGE_TAGS=$_DOCKERHUB_IMAGE_TAGS" >> $GITHUB_ENV
          echo "VERSION=$_VERSION" >> $GITHUB_ENV
      - name: Set environment DOCKERHUB_IMAGE_PLATFORMS
        run: |
          _DOCKERHUB_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
          if [ "${{ matrix.os }}" == "ubuntu" ]; then
            _DOCKERHUB_IMAGE_PLATFORMS+=",linux/arm/v7"
          fi
          echo "DOCKERHUB_IMAGE_PLATFORMS=$_DOCKERHUB_IMAGE_PLATFORMS" >> $GITHUB_ENV
      - name: Build and push
        if: env.DOCKERHUB_IMAGE_TAGS != ''
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ matrix.os }}
          tags: ${{ env.DOCKERHUB_IMAGE_TAGS }}
          labels: org.opencontainers.image.version=${{ env.VERSION }}
          platforms: ${{ env.DOCKERHUB_IMAGE_PLATFORMS }}
          push: true
